version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"

registries:
  maven-google:
    type: "maven-repository"
    url: "https://dl.google.com/dl/android/maven2"

  maven-central:
    type: "maven-repository"
    url: "https://repo.maven.apache.org/maven2"
